spring:
  application:
    name: clinica-vet
  h2:
    console:
      enabled: true
      path: '/h2'
  datasource:
    url: 'jdbc:h2:file:/home/dev/dbVet'
    username: 'sa'
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
springdoc:
  api-docs:
    path: '/api-docs'
