spring:
  application:
    name: clinica-vet
  h2:
    console:
      enabled: true
      path: '/h2'
<<<<<<< HEAD
=======

>>>>>>> 88dd87e348127999f2325fbeed26326a9f9facc0
  datasource:
    url: 'jdbc:h2:file:/home/dev/dbVet'
    username: 'sa'
    password: ''
    driver-class-name: org.h2.Driver
<<<<<<< HEAD
=======
    #url: 'jdbc:postgresql://localhost:5432/postgres'
    #username: 'postgres'
    #password: '56657131'
    #driver-class-name: org.postgresql.Driver

>>>>>>> 88dd87e348127999f2325fbeed26326a9f9facc0
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
<<<<<<< HEAD
=======

>>>>>>> 88dd87e348127999f2325fbeed26326a9f9facc0
springdoc:
  api-docs:
    path: '/api-docs'
